#!/bin/sh
# The next line is executed by /bin/sh, but not Tcl \
exec tclsh $0 ${1+"$@"}

# Directory containing tests.
set test_dir [file dirname [file normalize [info script]]]
set openroad_dir [file dirname $test_dir]

source [file join $test_dir "regression.tcl"]
source [file join $test_dir "regression_tests.tcl"]

set tool_errors 0

proc run_tool_tests { tool } {
  global tool_errors openroad_dir tool_scripts

  puts "------------------------------------------------------"
  puts $tool
  set script [dict get $tool_scripts $tool]
  set test [file join $openroad_dir $script]
  if { ![file exists $test] } {
    puts "Error: $script not found."
    incr tool_errors
  } elseif { [catch "exec $test >@stdout"] } {
    incr tool_errors
  }
}

proc define_tool_script { tool script } {
  global tool_scripts
  dict set tool_scripts [string tolower $tool] $script
}

# roughly flow order
define_tool_script "OpenDB" "src/odb/test/regression"
define_tool_script "dbSta" "src/dbSta/test/regression"
define_tool_script "stt" "src/stt/test/regression"
define_tool_script "ifp" "src/ifp/test/regression"
define_tool_script "tap" "src/tap/test/regression"
define_tool_script "ppl" "src/ppl/test/regression"
define_tool_script "pdn" "src/pdn/test/regression"
define_tool_script "pad" "src/pad/test/regression"
define_tool_script "mpl" "src/mpl/test/regression"
define_tool_script "mpl2" "src/mpl2/test/regression"
define_tool_script "par" "src/par/test/regression"
define_tool_script "gpl" "src/gpl/test/regression"
define_tool_script "rsz" "src/rsz/test/regression"
define_tool_script "cts" "src/cts/test/regression"
define_tool_script "dpl" "src/dpl/test/regression"
define_tool_script "dpo" "src/dpo/test/regression"
define_tool_script "grt" "src/grt/test/regression"
define_tool_script "ant" "src/ant/test/regression"
define_tool_script "rcx" "src/rcx/test/regression"
define_tool_script "psm" "src/psm/test/regression"
define_tool_script "drt" "src/drt/test/regression"
define_tool_script "rmp" "src/rmp/test/regression"
define_tool_script "upf" "src/upf/test/regression"
define_tool_script "utl" "src/utl/test/regression"
define_tool_script "fin" "src/fin/test/regression"
define_tool_script "dft" "src/dft/test/regression"
define_tool_script "gui" "src/gui/test/regression"

if { $argv == {} } {
  puts "Error: You must specify a tool name to run."
} else {
  foreach arg $argv {
    set arg [string tolower $arg]
    set matched 0
    
    dict for {tool script} $tool_scripts {
      if { [string match -nocase $arg $tool] } {
	run_tool_tests $tool
	set matched 1
      }
    }

    if { !$matched } {
      puts "$arg is not an openroad test or tool name."
      incr tool_errors
    }
  }
}

puts "------------------------------------------------------"
if { $tool_errors } {
  puts "Found $tool_errors tool regression failures."
} else {
  puts "Passed all tool regressions."
}

exit $tool_errors

# Local Variables:
# mode:tcl
# End:
